import '../styles/global.css';
import {Inter as FontSans} from 'next/font/google';

const fontSans = FontSans({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Welcome to user-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontSans.className}>{children}</body>
    </html>
  );
}
